import pipeclient
import os
import time
import random
import sys
if os.path.isfile("internal/INTENTIONS.TXT"):
	os.remove("internal/INTENTIONS.TXT")
if os.path.isfile("internal/text.txt"):
	os.remove("internal/text.txt")
os.system("pkill audacity")
os.system("pkill xvfb")
os.system("rm -r -f internal/temp1.mp3")
os.system("rm -r -f internal/temp2.mp3")
os.system("rm -r -f internal/temp3.flac")
os.system("rm -r -f internal/temp4.flac")
os.system("rm -r -f internal/temp5.flac")
os.system("rm -r -f internal/speech_441.mp3")
os.system("rm -r -f internal/temp1_.mp3")
os.system("rm -r -f internal/templayer.mp3")
os.system("rm -r -f internal/templayer.mp3")
os.system("gtts-cli --lang en --file text.txt -o internal/temp1.mp3 > /dev/null 2>&1")
lines = open('text.txt').readlines()
random.shuffle(lines)
open('text.txt', 'w').writelines(lines)
speed = input("Choose speed: normal, 2, 4, 8, or 16: ")
sys.stdout = open(os.devnull, 'w')
os.system("gtts-cli --lang en --file text.txt -o internal/templayer.mp3 > /dev/null 2>&1")
os.system('ffmpeg -y -i internal/temp1.mp3 -i internal/templayer.mp3 -filter_complex "[0:0]volume=1[a];[1:0]volume=1.0[b];[a][b]amix=inputs=2:duration=first:dropout_transition=0" -ac 2 -b:a 1M -crf 5 internal/templayer_.mp3 > /dev/null 2>&1')
if speed == "2":
	os.system('ffmpeg -i internal/templayer_.mp3 -filter:a "atempo=2.0" internal/temp1_.mp3 > /dev/null 2>&1')
if speed == "4":
	os.system('ffmpeg -i internal/templayer_.mp3 -filter:a "atempo=2.0, atempo=2.0" internal/temp1_.mp3 > /dev/null 2>&1')
if speed == "8":
	os.system('ffmpeg -i internal/templayer_.mp3 -filter:a "atempo=2.0,atempo=2.0,atempo=2.0" internal/temp1_.mp3 > /dev/null 2>&1')
if speed == "16":
	os.system('ffmpeg -i internal/templayer_.mp3 -filter:a "atempo=2.0,atempo=2.0,atempo=2.0,atempo=2.0" internal/temp1_.mp3 > /dev/null 2>&1')
os.system("rm internal/temp1.mp3 > /dev/null 2>&1")
os.system("ffmpeg -stream_loop -1 -i internal/temp1_.mp3 -c copy -t 1800 internal/temp2.mp3 > /dev/null 2>&1")
os.system("rm internal/temp1_.mp3 > /dev/null 2>&1")
os.system("rm internal/templayer.mp3 > /dev/null 2>&1")
os.system("rm internal/templayer_.mp3 > /dev/null 2>&1")
os.system('ffmpeg -y -i internal/temp2.mp3 -i internal/brook.mp3 -filter_complex "[0:0]volume=0.4[a];[1:0]volume=2.5[b];[a][b]amix=inputs=2:duration=first:dropout_transition=0" -ac 2 -b:a 1M -crf 5 internal/temp3.flac > /dev/null 2>&1')
os.system("ffmpeg -i internal/temp3.flac -af volume=3 -vcodec copy internal/temp4.flac > /dev/null 2>&1")
os.system("rm internal/temp3.flac > /dev/null 2>&1")
os.system('ffmpeg -i internal/temp4.flac -af "afade=t=in:st=0:d=5" internal/temp5.flac > /dev/null 2>&1')
os.system("rm internal/temp4.flac > /dev/null 2>&1")
os.system("ffmpeg -i internal/temp2.mp3 -ar 44100 internal/speech_441.mp3 > /dev/null 2>&1")
os.system("rm internal/temp2.mp3 > /dev/null 2>&1")
os.system("Xvfb :99 & > /dev/null 2>&1")
os.system ("DISPLAY=:99 prerequisites/audacity/build/audacity > /dev/null 2>&1 & disown audacity > /dev/null 2>&1")
time.sleep(20)
client = pipeclient.PipeClient()
cwd = os.getcwd()
client.write("Import2: Filename={}/internal/speech_441.mp3".format(cwd), timer=False)
time.sleep(20)
client.write("SelectAll", timer=False)
time.sleep(3)
client.write("ultrasonic", timer=False)
time.sleep(300)
client.write("Import2: Filename={}/internal/temp5.flac".format(cwd), timer=False)
time.sleep(20)
client.write("Export2: Filename={}/internal/temp6.flac NumChannels=2".format(cwd), timer=False)
os.system("rm internal/speech_441.mp3")
os.system("rm internal/temp5.flac")
os.system("cp text.txt internal/text.txt")
affirmations = open('internal/text.txt', 'r').read()
with open('internal/INTENTIONS.TXT', 'w') as f:
    f.write('Charge temp6.flac with the following, using Resonance Field and Anthro Black Hole:\n')
with open('internal/INTENTIONS.TXT', 'a') as f:
    f.write(affirmations)
os.system('internal/./intrpt -m 1 -i "NEST-100" -d 00:05:00 > /dev/null 2>&1')
os.system("mv internal/temp6.flac final_$(date +%F-%H:%M).flac > /dev/null 2>&1")
os.system("pkill audacity")
os.system("pkill xvfb")
os.remove("internal/INTENTIONS.TXT")
os.remove("internal/text.txt")
print(client.read())
